### ISSUE TITLE
remove Portals support

### ISSUE THREAD

**Issue by jeffhammond** [GlobalArrays/ga#108]
`src-portals` was for Cray XT.  I am not aware of any active Cray XT machines anymore.  In any case, Portals was always a very brittle port and the author/maintainer (Vinod) isn't working on ARMCI anymore so it's imprudent to give anyone the impression this feature is supported.

**Comment by jeffhammond** [comment]
This will be fixed by https://github.com/GlobalArrays/ga/pull/135.

**Comment by ajaypanyala** [comment]
resolved via #328
