### ISSUE TITLE
Problem with setting MKL libraryies

### ISSUE THREAD

**Issue by AndreyShtyrov** [GlobalArrays/ga#118]
Dear GlobalArrays cominuty,
I have tried install ga-5.6 with mkl intel studio 2018 on linux.  But during configuration script dont find MKL.
I have used this command : ... --with-blas8=$MKLROOT --enable-i8 --prefix=$HOME/local/dga5.6
and i set MPICC = mpicc and MPIF77 = mpiifort as enviroment variable.

**Comment by jeffdaily** [comment]
I second the request for the config.log, but also try `--with-blas8=-mkl` since you're using the intel compilers.  I recall we added support for that special icc flag that enables the MKL that is packaged with the compiler.

**Comment by AndreyShtyrov** [comment]
[config.log](https://github.com/GlobalArrays/ga/files/2294220/config.log)
