### ISSUE TITLE
deprecate TCGMSG4/5 and PVM, keep TCGMSG-MPI

### ISSUE THREAD

**Issue by jeffdaily** [GlobalArrays/ga#14]
We should assume at minimum an MPI runtime is linked in and in use.

TCGMSG4/5 are obsolete.  They should be removed from the code base including any preprocessor symbols.  TCGMSG4 uses 'pfiles' for running in parallel.  This complicates the Makefile test suite and should also be removed.

TCGMSG-MPI is the MPI compatibility layer and is always compiled.  This has been the transition path for many years now.  For example, NWChem can continue to use PBEGIN() as part of TCGMSG-MPI as needed.

There are a few lingering references to PVM that should be removed.

These changes would also let us remove dead code where the preprocessor symbol MSG_COMMS_MPI is used throughout the code.

**Comment by jeffhammond** [comment]
This is will partially resolved by https://github.com/GlobalArrays/ga/pull/135
