### ISSUE TITLE
pointer type mismatch tcgi_argc in tcgmsg-mpi

### ISSUE THREAD

**Issue by drew-parsons** [GlobalArrays/ga#155]
In tcgmsg/tcgmsg-mpi/misc.c, tcgi_argc is defined as `int`.

    int      tcgi_argc=0;

In nxtval-armci.c it is declared as a pointer,

    extern int     *tcgi_argc;

I guess misc.c should be updated to

    int      *tcgi_argc=NULL;

or somesuch?

This was reported in the Debian Bug System, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820677

**Comment by jeffhammond** [comment]
I'm curious if that code is even used.  There are some many things wrong with it.

**Comment by edoapra** [comment]
Addressed by https://github.com/GlobalArrays/ga/commit/791926f6b5663038aeab0c0d93c61ede3150ae00
