### ISSUE TITLE
Can a compiled GA library be used to detect its compile-time ARMCI setting?

### ISSUE THREAD

**Issue by srk** [GlobalArrays/ga#165]
I'm wondering if it possible to write code that detects some library metadata, specifically the ARMCI compile-time setting used to compile GA libraries. I need to be able to detect programmatically if MPI-PR has been specified when the GA library was compiled.

**Comment by jeffhammond** [comment]
There may be a better way, but at least with MPI-PR, you should be able to compare `int np = GA_Nnodes()` to `MPI_Comm_size(MPI_COMM_WORLD, &size)`.  For MPI-PR, they should not be equal (`np != size`).

ARMCI-MPI with Casper underneath does a similar trick to MPI-PR but intercepts all the MPI symbols so the two queries about will produce the same output.
