### ISSUE TITLE
autoconf cppflags broken

### ISSUE THREAD

**Issue by ajmay81** [GlobalArrays/ga#181]
Commit 3d13d03620cf7333e1fd6bb6fef1b653a0d5b42c  contains an error, and although it has my name as author it is not the same as the actual commit made in #161 . It appears there was a conflict with newly introduced SICM_CPPFLAGS, and whoever dealt with that inserted a newline in the middle of the variable, the result is:

```
> ga-config --cppflags
@SICM_CPPFLAGS@ -I/opt/ga/5.8/mpich-3.3.2-gcc-10.2.0/include
```

which cannot be used.

**Comment by edoapra** [comment]
@ajmay81 I am the guy responsible for having modified your original pull request
Thanks for reporting this issue
