### ISSUE TITLE
rename MPI_Check

### ISSUE THREAD

**Issue by jeffhammond** [GlobalArrays/ga#2]
`MPI_Check` violates the MPI standard because it uses the reserved `MPI_` namespace.

This does not break anything in practice and thus is low priority, but it is also a trivial fix.

**Comment by ajaypanyala** [comment]
this was resolved a while ago with [8f3b2d8](https://github.com/GlobalArrays/ga/commit/8f3b2d85d641eedc6cd4105a169dd6ad70779879)
