### ISSUE TITLE
Failed to build GA on release branch for 404 error.

### ISSUE THREAD

**Issue by haohaiyu** [GlobalArrays/ga#225]
Steps to repro:

git clone https://github.com/GlobalArrays/ga.git
cd ga
git checkout release/5.8 (or other version or just use the master branch)
./autogen.sh

And the error messages are attached:

[ga.log](https://github.com/GlobalArrays/ga/files/7086745/ga.log)

**Comment by edoapra** [comment]
Issue addressed by commit https://github.com/GlobalArrays/ga/commit/2d950ef898878ba53b45adb83508024498d29e27
