### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by temcdrm** [GlobalArrays/ga#235]
Trying to build ga from the master branch, for GridPACK, on Ubuntu 20.04 LTS.  It stops for several undeclared functions in GlobalArray.cc, the first of which is: 

```
ga++/src/GlobalArray.cc:268:10: error: ‘GA_Deallocate’ was not declared in this scope; did you mean ‘GA_Allocate’?
  268 |   return GA_Deallocate(mHandle);
      |          ^~~~~~~~~~~~~
      |          GA_Allocate
```
That function does not seem to be declared in a header file:
```
tom@uvm:~/src/ga$ grep -r GA_Deallocate *
ga++/src/GlobalArray.cc:  return GA_Deallocate(mHandle);
global/src/capi.c:int GA_Deallocate(int g_a)
global/src/capi.c:int NGA_Deallocate(int g_a)
```
My configure command was this:
```
./configure --enable-i4 --without-blas --enable-cxx --with-mpi-ts --disable-f77 --prefix=/home/tom/gridpack/ga
```
Any suggestions to fix this would be welcome.

**Comment by jeffhammond** [comment]
I could not reproduce with the `develop` branch, so you might try that.

**Comment by jeffhammond** [comment]
I see the issue on `master`.  I recommend you just use `develop`.

**Comment by temcdrm** [comment]
That works for me; thank you.  Leaving this for someone else to close, as presumably the master branch should eventually build.

**Comment by jeffhammond** [comment]
master always lags behind develop. The fix for master is to merge develop. @bjpalmer should do that.

**Comment by bjpalmer** [comment]
That should work in master since I added the deallocate operation before the 5.8.1 release. I'll check it out, but in the meantime, I'd use develop.

**Comment by bjpalmer** [comment]
I pushed some changes to the draft 5.8.1 release that seem to fix the problem.
