### ISSUE TITLE
CMake not building Scalapack interface

### ISSUE THREAD

**Issue by edoapra** [GlobalArrays/ga#24]
I could not find any way to build the GA Scalapack interface in the current CMake infrastructure

**Comment by abhinavvishnu** [comment]
Bruce -- I believe that you were working on this. Please let us know when the fix is available.

**Comment by bjpalmer** [comment]
I've modified the build to use ScalaPACK. This hasn't been aggressively tested so it will probably need to be tweaked further. Currently, to build with ScalaPACK, add

-D ENABLE_SCALALPACK:BOOL=TRUE

as one of the CMake configuration options. Also, you need to add the ScalaPACK libraries directly to the build using the

-D GA_EXTRA_LIBS:STRING='.......'

option. Currently, this looks like

-D GA_EXTRA_LIBS:STRING='-L$MKLROOT/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -liomp5 -lm'

on constance using the intel compilers and MPI.

**Comment by ajaypanyala** [comment]
This is fixed in `develop` now.
