### ISSUE TITLE
cache_test is taking a long time

### ISSUE THREAD

**Issue by mbanck** [GlobalArrays/ga#242]
Running the testsuite, I noticed that most tests seem to be reasonably fast, but `global/testing/cache_test.x`  is taking a long time, about 15 minutes on my notebook (Lenovo 14s 2nd Gen AMD).

Is that unavoidable, or could this be sped up somehow, without loss of test coverage?

**Comment by bjpalmer** [comment]
Sorry about the incredibly late response, this issue fell through the cracks. I believe this test has always taken a fairly long time.
