### ISSUE TITLE
remove/replace gai_malloc() and gai_free()

### ISSUE THREAD

**Issue by jeffdaily** [GlobalArrays/ga#26]
We likely don't really need these since we can use valgrind or other utilities for checking invalid reads/writes.

**Comment by jeffhammond** [comment]
`git cherry-pick 52525663987c4c86925cc6ddb090c6a2519764c0`? 😃 
 (https://github.com/GlobalArrays/ga/pull/4/commits/52525663987c4c86925cc6ddb090c6a2519764c0)

**Comment by jeffdaily** [comment]
Truth be told, I've just made an issue out of most of the things you've done in your pull #4.  I will cherry-pick as much as I can to resolve these, but I wasn't ready to bite off the entire pull request.  I'm probably being overly conservative and merge conflicts are painful.  Our develop branch now reflects the 5.6 release where we have removed generated autotools files from the repository, so that is fixed at least, though your pull request does also feature removing the generated files.  Also, for better or worse, I wasn't ready to commit to C99 as a base language level, so that rules out the for loop scoping of the loop counters in many of your code changes.

**Comment by jeffhammond** [comment]
Yeah, I figured that out after I saw the series.  Makes perfect sense to me.  My changes were poorly organized and it is ideal to redo them from scratch.  It will be tedious but has the long-term benefit of making the Git history sensible.

**Comment by jeffhammond** [comment]
Yeah, I love C99 but can't convince anyone to assume it because of at least one stupid compiler that doesn't support it.

**Comment by jeffhammond** [comment]
This was fixed by https://github.com/GlobalArrays/ga/commit/d97c9becf8eab515a64841cb631056558e2c4918
