### ISSUE TITLE
Missing libraries after building

### ISSUE THREAD

**Issue by januspmzh** [GlobalArrays/ga#262]
Hi GA developer,

I am trying to build a GA with global, ma, tcgmsg, and tcgmsg-mpi modules with intel compiler, intelmpi and mkl library. After building, I couldn't find libma.a, lib global.a and libtcgmsg-mpi.a anywhere in the build. 

The configure command I used is: ../configure MPICC=mpiicc CC=icc F77=ifort F90=ifort MPICXX=mpiicpc MPIF77=mpiifort MPIF90=mpiifort CXX=icpc --with-mpi=/software/intel/parallel_studio_xe_2018_update4/impi/2018.4.274 --with-ma --with-global --with-tcgmsg --with-tcgmsg-mpi --with-sockets --with-blas=-mkl --with-lapack=-mkl

Any help would be extremely helpful!

Thanks,
Zihan

**Comment by edoapra** [comment]
@januspmzh Could you upload the `config.log` file?

**Comment by januspmzh** [comment]
Hi, sorry for this late reply, I got this worked out earlier, there are some libs depreciated earlier, thanks!
