### ISSUE TITLE
how to create ga whose number of elements is larger than INT_MAX

### ISSUE THREAD

**Issue by jsboer** [GlobalArrays/ga#269]
HI, I find that creatGA only support int dims[], how can I create a one-dimension gloabl array whose number of elements is larger than INT_MAX?

Thank you!

**Comment by jeffhammond** [comment]
See https://github.com/GlobalArrays/ga/blob/master/global/src/ga.h#L373.  I am sorry for the lack of documentation, even though it's not my fault.

**Comment by jsboer** [comment]
Oh! Thank you !
