### ISSUE TITLE
Issue building with MPItrampoline

### ISSUE THREAD

**Issue by nick-wilson** [GlobalArrays/ga#285]
I'm trying to build Global Arrays with [MPItrampoline](https://github.com/eschnett/MPItrampoline) in order to produce more portable binaries, however the compilation fails.

I've opened an issue at https://github.com/eschnett/MPItrampoline/issues/34

Any insight you can provide would be appreciated.

**Comment by jeffhammond** [comment]
This is a bug in MPItrampoline.  We can discuss on the linked issue.  Thanks for bringing this to my attention, since I care a great deal about this topic.

**Comment by jeffhammond** [comment]
Reopening issue, because the MPI standard is ambiguous, and it's easy enough for me to convert case-switch to if-elif.

**Comment by jeffhammond** [comment]
did https://github.com/GlobalArrays/ga/pull/286 fix this? i can't remember.
