### ISSUE TITLE
two copies of global.fh.in

### ISSUE THREAD

**Issue by edoapra** [GlobalArrays/ga#303]
Why do we have two copies of `global.fh.in`?
```
% find . -name "g*fh*in"
./cmake/global.fh.in
./global/src/global.fh.in
```

**Comment by ajaypanyala** [comment]
fixed via [3b931bb](https://github.com/GlobalArrays/ga/commit/3b931bbfcc2931de74b8bb37e5a0bf9c774ce3eb)
