### ISSUE TITLE
GA 5.6 release - autotools are downloaded and built even when latest versions exist

### ISSUE THREAD

**Issue by ajaypanyala** [GlobalArrays/ga#33]
When trying to build GA-5.6 release tarball - autoconf2.69, automake 1.11 and libtool 2.4.6 are downloaded and built even when these versions exist.

**Comment by abhinavvishnu** [comment]
Hi Jeff:

Ajay recently pointed out to this. Can you please take care of it?

Thanks,

:- Abhinav

**Comment by jeffhammond** [comment]
I know I am not the Jeff you meant, but I will try to work on this as well.  Given how many places I use that script, I have a selfish interest in making it as efficient as possible 😉

**Comment by jeffdaily** [comment]
Something else to check in the script -- I just heard from a colleague that the script fails to download the various tarballs due to port restrictions.  They're able to git clone the repo just fine, but wget fails.  I also tried, but the problem is that the FTP port is blocked.  I'm not sure how to resolve this unless there is another URL for downloading the tarballs.

**Comment by ajaypanyala** [comment]
M4_VERSION_MIN is set to 1.4.12. When the script finds m4 say v1.4.13 on the system, it proceeds to download and install autoconf-2.69, but the autoconf configure script fails with the error

> checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH. 
> GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
> GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
> Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
> FAILURE 3

I set M4_VERSION_MIN=1.4.16 to avoid this error (M4-1.4.17 gets downloaded and built)

**Comment by jeffdaily** [comment]
I've tried to fix this in the hotfix/5.6.1 branch.  I hope it's working better now.

**Comment by ajaypanyala** [comment]
It works now. Thanks Jeff!
