### ISSUE TITLE
#ifdef ENABLE_EISPACK should be #if ENABLE_EISPACK

### ISSUE THREAD

**Issue by jeffdaily** [GlobalArrays/ga#38]
rsg.F and ga_diag_seq.F use `#ifdef ENABLE_EISPACK`, and since config.h unconditionally defines ENABLE_EISPACK to either 0 or 1, we're stuck using the old EISPACK code.  Update these two source files to use `#if ENABLE_EISPACK` instead.

**Comment by bjpalmer** [comment]
The #ifdef ENABLE_EISPACK have all been replaced with #if ENABLE_EISPACK.
