### ISSUE TITLE
develop branch and m4 version on cascade

### ISSUE THREAD

**Issue by edoapra** [GlobalArrays/ga#41]
m4 version 1.4.13 on cascade does not work
 modified travis/install-autotools.sh t get 1.4.16
 M4_VERSION_MIN=1.4.16

**Comment by edoapra** [comment]
I have just realized that this issue has been already been mentione by Ajay in
https://github.com/GlobalArrays/ga/issues/33#issuecomment-295496535

**Comment by jeffdaily** [comment]
No worries.  I've been working on a fix for it this week in addition to other build issues to go out as a v5.6.1 release.  Changes are currently in hotfix/5.6.1 branch.  See
https://github.com/GlobalArrays/ga/compare/hotfix/5.6.1
for current changes.

**Comment by abhinavvishnu** [comment]
Edo -- can you please do a quick code review?

**Comment by edoapra** [comment]
Sure. hotfix/5.6.1 correctly builds the needed version of m4 on cascade
