### ISSUE TITLE
Compiler error with --with-ofi

### ISSUE THREAD

**Issue by opoplawski** [GlobalArrays/ga#5]
Trying to build in fedora rawhide --with-ofi:
```
src-ofi/comex.c: In function 'getputs_stride':
src-ofi/comex.c:2212:63: error: dereferencing pointer to incomplete type 'const struct iovec'
         msg->msg_iov = malloc(ofi_data.rma_iov_limit * sizeof(*msg->msg_iov));
                                                               ^~~~~~~~~~~~~
```
Full log at https://kojipkgs.fedoraproject.org//work/tasks/4498/18404498/build.log

**Comment by jeffhammond** [comment]
What network are you targeting?  The OFI implementation has some limitations...

**Comment by jeffdaily** [comment]
I just merged a pull request from the author of the OFI implementation.  It's currently in the 'release/5.6' branch if you want to try it.

**Comment by abhinavvishnu** [comment]
@jeffdaily is it OK to close this issue?
