### ISSUE TITLE
install-autotools.sh on osx might choke if no timeout tool

### ISSUE THREAD

**Issue by jeffdaily** [GlobalArrays/ga#50]
install-autotools.sh assumes 'gtimeout' to be installed -- this works for Travis CI since we `brew install coreutils`.  This doesn't work for non-travis builds.

8344449a774f11bc791926307c8d7a3d2bb90a77 attempts to fix this.

@edoapra can you verify if I fixed this?

**Comment by edoapra** [comment]
Yes, it works fine on my MacOS Sierra box
