### ISSUE TITLE
KNL: icc -xmic-avx512  breaks src-mpi-pr/comex.c

### ISSUE THREAD

**Issue by edoapra** [GlobalArrays/ga#51]
I have observed this issue on Cray KNLs when the module craype-mic-knl is loaded. craype-mic-knl triggers the -xmic-avx512 icc option that seems to generate erroneous code out of src-mpi-pr/comex.c
The problem can be reproduced with any NWChem run. I have not tried comex/ga tests, which one should I try?

**Comment by jeffhammond** [comment]
Can this be closed?  It seems to have been resolved a while ago.

**Comment by edoapra** [comment]
Yes, it was
