### ISSUE TITLE
Testing Global Arrays on Intel KNL + Omnipath

### ISSUE THREAD

**Issue by abhinavvishnu** [GlobalArrays/ga#8]
Test xGA on Intel KNL and Omni-path system available on TACC.

**Comment by jeffhammond** [comment]
@jeffdaily Did you ever get access to the Intel OPA system?  That's another way to address this issue.  Additionally, I have access to a few OPA clusters internally if nothing else works.

**Comment by abhinavvishnu** [comment]
We have tested the MPI-3 and MPI-PR port on NERSC systems. However, it does not have Omnipath but Aries interconnect.

JeffH -- Can you please test it on your internal system, currently I do not have access to the Omni-path system (or at least have any hours on it).

Thanks,

:- Abhinav

**Comment by jeffhammond** [comment]
Sure, I can test on a bunch of machines like this with different MPI libs
and +/- SLURM.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/
