### ISSUE TITLE
Automake regex expression broken for Perl versions >=5.26.0 

### ISSUE THREAD

**Issue by keipertk** [GlobalArrays/ga#88]
Running autogen.sh with Perl v5.26.1 gives:

`Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /home/kris/ga/autotools/bin/automake line 4159.`

See here:
http://search.cpan.org/dist/perl-5.26.0/pod/perldelta.pod#Unescaped_literal_"{"_characters_in_regular_expression_patterns_are_no_longer_permissible

**Comment by ajaypanyala** [comment]
@jeffdaily I see this error too when using perl v5.26

**Comment by jeffdaily** [comment]
This is fixed by e94963d2cd960e11c52ad60d9b33f23af336903b.  Only in the develop branch.

Are you using master or develop or some other branch or release?

**Comment by ajaypanyala** [comment]
I was using the 5.6.2 release. Will try develop. Thanks!

**Comment by jeffdaily** [comment]
If you are using a downloaded release tarball, it should have the configure scripts already generated for you.  Make sure to download *OUR* tarball and not the tarball generated automatically by github.  Unless you were needing to edit the configure.ac or Makefile.am files, this should be sufficient for most user's needs.

For example:
https://github.com/GlobalArrays/ga/releases/download/v5.6.2/ga-5.6.2.tar.gz

![image](https://user-images.githubusercontent.com/904248/31840204-236ea144-b599-11e7-9ae9-8cbf28f24936.png)

**Comment by ajaypanyala** [comment]
Yes, I am using the 5.6.2 release tarball pointed above.

**Comment by jeffdaily** [comment]
What was your reason for rerunning ./autogen.sh ?  Did we poorly document when to use it and when not to?

**Comment by ajaypanyala** [comment]
Rerunning? I quite din't get this part. I ran it only once before the configure step.

**Comment by jeffdaily** [comment]
If you download a release tarball like I described previously, you shouldn't have to run ./autogen.sh at all.  The ./autogen.sh script creates the necessary configure script, Makefile.in, etc, but is only necessary to run if the configure script doesn't already exist.  The configure script should exist in our release tarballs.  If it doesn't, this is a mistake and the tarball needs to be recreated by me.

**Comment by ajaypanyala** [comment]
Thanks for pointing it out. I did not realize that it pre-exists in release tarball. I was playing with github master for some time and then switched to the release tarball at some point - but continued running autogen.sh out of habit.
