### ISSUE TITLE
autogen fails on Mac 10.12

### ISSUE THREAD

**Issue by kipeters** [GlobalArrays/ga#89]
When attempting to install Ga (for my Molpro distribution), I execute the following:

```
git clone https://github.com/GlobalArrays/ga.git
cd ga
./autogen.sh
```

then failure:
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
main::scan_file() called too early to check prototype at /Users/kipeters/Molpro/src/ga/autotools/bin/aclocal line 643.
aclocal: couldn't open directory '/Users/kipeters/Molpro/src/ga/autotools/share/aclocal': No such file or directory
```
somewhat above this:
```
libtool found and is exactly needed version (2.4.6)
```

**Comment by kipeters** [comment]
sorry about the formatting, didn't know the pound signs would do that....

**Comment by jeffdaily** [comment]
Is this related to #88 ?  I just pushed a fix for it in the develop branch.  Could you try it and see if it was related?

**Comment by kipeters** [comment]
nope, but what did work was to delete my previously installed libtool (even though it was the correct version) and let the ga installer download and build one itself.

**Comment by jeffdaily** [comment]
Thank you for this report, as well as the work-around.  I have attempted to add osx 10.12 to the travis build of the develop branch to catch errors like this and #88 .  I don't expect us to overhaul the build system.  It is a bit fragile only in that it is known to work only with specific autotool versions, so we might just force the building of all of them for developers regardless of the versions matching.

**Comment by kipeters** [comment]
The latter sounds like a very good (very safe) path forward.

**Comment by jeffhammond** [comment]
@kipeters I edited your issue with (what I consider to be) better markup.  Click on the edit button to see what changes were made if you are interested in formatting tricks.

**Comment by kipeters** [comment]
Thanks Jeff!

**Comment by jeffdaily** [comment]
For the upcoming 5.6.4 release we have forced the install-autotools.sh script to install all autotools regardless of any versions found locally.  This should fix this issue.
