### ISSUE TITLE
Scalapack with 8-byte integers?

### ISSUE THREAD

**Issue by traktofon** [GlobalArrays/ga#93]
GA has the option `--with-scalapack8` to build it with a Scalapack that uses 8-byte integers. I guess Intel MKL provides such a Scalapack, but as far as I can tell, the Scalapack from Netlib has no official support for 8-byte integers. On https://community.amd.com/thread/159540 someone quotes "people in the Netlib community" that

> this will require grinding through all the BLACS and SCALAPACK code and modifying it to handle 64-bit integers.   

which apparently hasn't happened since there has been no release of Scalapack since then. Can anyone confirm that this is indeed the case? That basically `--with-scalapack8` requires MKL? Or did anyone manage with Netlib's Scalapack?

**Comment by edoapra** [comment]
Yes, --with-scalapack8 does require MKL
