### ISSUE TITLE
../../ga-5.6.3/comex/src-mpi-pr/comex.c:996: _generate_shm_name: Assertion `snprintf_retval < (int)31' failed

### ISSUE THREAD

**Issue by edoapra** [GlobalArrays/ga#95]
If _generate_shm_name is called more than 999999 times, the snprintf format runs out of digits.
A user running NWChem with thousand of runs in the same job reported this problem.
Adding the line 
```    if(counter > 999999) counter=0;```
might avoid the wrap-around problem, but I am not quite sure if this is the right fix for it.
The GA version used was 5.6.3

**Comment by jeffhammond** [comment]
Allocating shared-memory a million times sounds like a bad idea on many levels.  Maybe we should implement a memory pool or lazy deallocation for this.

**Comment by jeffdaily** [comment]
Patches welcome!

Perhaps we over-corrected a bit from our ARMCI days.  Instead of allocating a huge pinned chunk, we opted to just allocate as-needed, exactly the size needed.

**Comment by jeffhammond** [comment]
@jeffdaily I can provide a patch that uses `MPI_Win_allocate_shared` so that this becomes the problem of the MPI library, but I don't expect to have time to do the more complicated solutions any time soon.

**Comment by jeffdaily** [comment]
We provided a solution that should work for the time being.  Part of the 5.6.4 release.
