### ISSUE TITLE
additional arguments for bin/ga-config describing the presence of Peigs and/or Scalapack interfaces

### ISSUE THREAD

**Issue by edoapra** [GlobalArrays/ga#99]
It would be useful to add two new arguments to ga-config that print information about the Peigs and Scalapack interfaces. For example
--use_scalapack
--use_peigs
The should return an empty string when no interface is present and 1 (or Y) when it is present

**Comment by jeffdaily** [comment]
Fixed in 926756274904f01c67dec955e7b954a601712cc4.  Will become 5.6.5 release.
